### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by Hiillostaja** [cbdelavenne/fb-messenger-media-scraper#12]
login crashes

**Comment by loismarcin** [comment]
Same for me, tested with 2 accounts ! 😗

Attempt #1 failed, retrying
Traceback (most recent call last):
  File "C:\Users\lm\AppData\Local\Programs\Python\Python310\lib\site-packages\fbchat\_client.py", line 205, in login
    self._state = State.login(
  File "C:\Users\lm\AppData\Local\Programs\Python\Python310\lib\site-packages\fbchat\_state.py", line 153, in login
    raise _exception.FBchatUserError(
fbchat._exception.FBchatUserError: Login failed. Check email/password. (Failed on url: https://m.facebook.com/login.php?login_attempt=1)
Attempt #2 failed, retrying

etc...
